@istest
public class ET_InspectionCancellationTest {
    static testmethod void inspeccancellation(){
        
        ET_InspectionCancellation inspcan = new ET_InspectionCancellation();
        ET_InspectionCancellation.Control inspcancl = new ET_InspectionCancellation.Control();
        ET_InspectionCancellation.Input inspinput = new ET_InspectionCancellation.Input();
        inspinput.AmanReceiptNo = '1234';
        ET_InspectionCancellation.Output inspoutpt = new ET_InspectionCancellation.Output();
        
        
        
        
    }
}